// @ts-nocheck
import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import axios from'axios';import{Alert,Box,Button,Card,CardContent,Drawer,List,ListItemButton,ListItemText,MenuItem,Stack,TextField,Typography}from'@mui/material';import'./style.css';
const api=axios.create();
function App(){
 const[uid,setUid]=useState<number>(),[login,setLogin]=useState('eduardo'),[password,setPassword]=useState('eduardo86'),[page,setPage]=useState('D-1001'),[entities,setEntities]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[eid,setEid]=useState(1),[message,setMessage]=useState(''),[file,setFile]=useState<File>(),[uploadResult,setUploadResult]=useState<any>(),[uf,setUf]=useState({login:'',password:'',name:''}),[ef,setEf]=useState({cnpjRoot:'',legalName:''});
 const load=async()=>{try{const[u,e]=await Promise.all([api.get('/api/admin/users'),api.get('/api/admin/entities')]);const userList=Array.isArray(u.data)?u.data:[];const entityList=Array.isArray(e.data)?e.data:[];setUsers(userList);setEntities(entityList);if(entityList[0])setEid(x=>entityList.some(y=>y.id===x)?x:entityList[0].id)}catch{setMessage('Falha ao carregar cadastros')}};useEffect(()=>{api.get('/api/admin/entities').then(r=>setEntities(Array.isArray(r.data)?r.data:[])).catch(()=>{})},[]);
 async function signIn(){try{const r=await api.post('/api/auth/login',{login,password});setUid(r.data.userId);setMessage('');await load()}catch{setMessage('Login inválido')}}
 async function upload(){if(!file){setMessage('Selecione um XML ou ZIP');return}try{const f=new FormData();f.append('file',file);const r=await api.post('/api/layouts/d1001/import',f,{headers:{'X-User-Id':uid,'X-Entity-Id':eid}});setUploadResult(r.data);setMessage(r.data.invalidCount?'Críticas encontradas no lote D-1001':'Lote D-1001 validado sem críticas')}catch(e){setMessage(e.response?.data?.message||'Falha no upload/validação')}}
 function downloadReport(){if(!uploadResult?.reportCsv)return;const blob=new Blob([uploadResult.reportCsv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`criticas-d1001-lote-${uploadResult.batchId}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(!uid)return <Box sx={{maxWidth:420,m:'80px auto'}}><Card><CardContent><Typography variant="h4" mb={3}>DeRE POC — Acesso</Typography><Stack spacing={2}><TextField label="Login" value={login} onChange={e=>setLogin(e.target.value)}/><TextField label="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Button variant="contained" onClick={signIn}>Entrar</Button>{message&&<Alert>{message}</Alert>}</Stack><Typography mt={3} color="text.secondary">Carga local: eduardo / eduardo86</Typography></CardContent></Card></Box>;
 const menu=['D-1001','D-1011','D-1101','D-1106','D-1121','D-2101','D-1199','Usuários','Entidades','Associações','Certificados','Relatórios'];
 const entitySelect=<TextField select fullWidth label="Entidade" value={eid} onChange={e=>setEid(+e.target.value)}>{entities.map(e=><MenuItem key={e.id} value={e.id}>{e.legalName} — {e.cnpjRoot}</MenuItem>)}</TextField>;
 const critiques=(uploadResult?.files||[]).flatMap((f:any)=>(f.issues||[]).map((i:any)=>({fileName:f.fileName,eventId:f.eventId,...i})));
 const d1001Import=<Card><CardContent><Stack spacing={2}>{entitySelect}<Typography>Envie um XML individual ou um lote ZIP contendo XMLs do layout D-1001.</Typography><input type="file" accept=".xml,.zip" onChange={e=>setFile(e.target.files?.[0])}/><Button variant="contained" onClick={upload}>Analisar, validar e persistir</Button>{uploadResult&&<Box><Typography>Lote #{uploadResult.batchId} — {uploadResult.sourceName}</Typography><Typography>Arquivos: {uploadResult.fileCount} | válidos: {uploadResult.validCount} | inválidos: {uploadResult.invalidCount}</Typography>{(uploadResult.files||[]).filter((f:any)=>f.parsed).map((f:any)=><Typography key={f.fileName+f.eventId}>Objeto D-1001: {f.fileName} · id {f.parsed.id} · CNPJ {f.parsed.cnpjRoot} · operação {f.parsed.operation} · vigência {f.parsed.validFrom}</Typography>)}<Button variant="outlined" onClick={downloadReport}>Baixar relatório CSV</Button>{critiques.length>0&&<Box component="table" sx={{width:'100%',borderCollapse:'collapse',mt:2}}><Box component="thead"><Box component="tr">{['Arquivo','Evento','Campo','Linha','Crítica'].map(h=><Box component="th" key={h} sx={{textAlign:'left',borderBottom:'1px solid #ccc',py:1,pr:2}}>{h}</Box>)}</Box></Box><Box component="tbody">{critiques.map((c:any,i:number)=><Box component="tr" key={i}><Box component="td" sx={{py:1,pr:2,borderBottom:'1px solid #eee'}}>{c.fileName}</Box><Box component="td" sx={{pr:2,borderBottom:'1px solid #eee'}}>{c.eventId}</Box><Box component="td" sx={{pr:2,borderBottom:'1px solid #eee'}}>{c.field}</Box><Box component="td" sx={{pr:2,borderBottom:'1px solid #eee'}}>{c.line||''}</Box><Box component="td" sx={{borderBottom:'1px solid #eee'}}>{c.message}</Box></Box>)}</Box></Box>}</Box>}</Stack></CardContent></Card>;
 const editUser=async(id)=>{const u=users.find(x=>x.id===id);const name=window.prompt('Nome do usuário',u?.name||'');if(name===null)return;const newPassword=window.prompt('Nova senha (deixe vazio para manter)', '')||'';await api.put(`/api/admin/users/${id}`,{login:u.login,name,password:newPassword});await load();setMessage('Usuário atualizado')};
 const editEntity=async(id)=>{const e=entities.find(x=>x.id===id);const legalName=window.prompt('Razão social',e?.legalName||'');if(legalName===null)return;const cnpjRoot=window.prompt('CNPJ raiz',e?.cnpjRoot||'');if(cnpjRoot===null)return;await api.put(`/api/admin/entities/${id}`,{cnpjRoot,legalName});await load();setMessage('Entidade atualizada')};
 return <Box sx={{display:'flex'}}><Drawer variant="permanent"><Typography sx={{p:2,fontWeight:700}}>DeRE EFPC</Typography><List>{menu.map(x=><ListItemButton selected={page===x} onClick={()=>setPage(x)} key={x}><ListItemText primary={x}/></ListItemButton>)}</List></Drawer><Box component="main" sx={{ml:'240px',p:4,width:'100%'}}><Typography variant="h4" mb={3}>{page}</Typography>{page==='D-1001'?d1001Import:page==='Usuários'?<Crud rows={users.map(u=>({id:u.id,label:`${u.login} — ${u.name}`}))} form={<><TextField label="Login" value={uf.login} onChange={e=>setUf({...uf,login:e.target.value})}/><TextField label="Nome" value={uf.name} onChange={e=>setUf({...uf,name:e.target.value})}/><TextField label="Senha" type="password" value={uf.password} onChange={e=>setUf({...uf,password:e.target.value})}/></>} onCreate={async()=>{await api.post('/api/admin/users',uf);setUf({login:'',password:'',name:''});load()}} onEdit={editUser} onDelete={async id=>{await api.delete(`/api/admin/users/${id}`);load()}}/>:page==='Entidades'?<Crud rows={entities.map(e=>({id:e.id,label:`${e.legalName} — ${e.cnpjRoot}`}))} form={<><TextField label="CNPJ raiz" value={ef.cnpjRoot} onChange={e=>setEf({...ef,cnpjRoot:e.target.value})}/><TextField label="Razão social" value={ef.legalName} onChange={e=>setEf({...ef,legalName:e.target.value})}/></>} onCreate={async()=>{await api.post('/api/admin/entities',ef);setEf({cnpjRoot:'',legalName:''});load()}} onEdit={editEntity} onDelete={async id=>{await api.delete(`/api/admin/entities/${id}`);load()}}/>:page==='Associações'?<Card><CardContent><Stack spacing={2}><TextField select fullWidth label="Usuário" value={uid} onChange={()=>{}}><MenuItem value={uid}>Usuário atual</MenuItem></TextField>{entitySelect}<Button variant="contained" onClick={async()=>{try{await api.post(`/api/admin/users/${uid}/entities/${eid}`);setMessage('Associação criada')}catch{setMessage('Falha na associação')}}}>Criar associação</Button></Stack></CardContent></Card>:<Alert severity="info">Menu {page} disponível. A ingestão XML/ZIP valida os layouts reconhecidos pelos XSDs oficiais.</Alert>}{message&&<Alert sx={{mt:2}}>{message}</Alert>}</Box></Box>}
 function Crud(p:any){return <Card><CardContent><Stack spacing={2}>{p.form}<Button variant="contained" onClick={p.onCreate}>Cadastrar</Button>{p.rows.map((r:any)=><Box key={r.id} sx={{display:'flex',alignItems:'center',gap:1,justifyContent:'space-between',p:1,borderBottom:'1px solid #ddd'}}><Typography sx={{flex:1}}>{r.label}</Typography><Button onClick={()=>p.onEdit(r.id)}>Editar</Button><Button color="error" onClick={()=>p.onDelete(r.id)}>Excluir</Button></Box>)}</Stack></CardContent></Card>}
 createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
